-- +goose Up
-- +goose StatementBegin
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mmo') THEN
        CREATE ROLE mmo WITH LOGIN PASSWORD 'mmo' CREATEDB CREATEROLE;
    ELSE
        ALTER ROLE mmo WITH LOGIN PASSWORD 'mmo' CREATEDB CREATEROLE;
    END IF;
END
$$;
-- +goose StatementEnd

GRANT ALL PRIVILEGES ON DATABASE mmo TO mmo;
GRANT ALL PRIVILEGES ON SCHEMA public TO mmo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO mmo;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO mmo;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO mmo;
GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public TO mmo;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO mmo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO mmo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO mmo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON ROUTINES TO mmo;

-- +goose Down

-- Intentionally left blank — revoking grants and dropping the role is destructive
